-- User table
CREATE TABLE [USER] (
    USER_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SURNAME VARCHAR(50) NOT NULL,
    DOB DATE,
    DIABETES_TYPE VARCHAR(20),
    MEDICATION VARCHAR(25),
    UNIT VARCHAR(10),
    POST_CODE VARCHAR(10),
    CITY VARCHAR(50)
);

-- Location table
CREATE TABLE [LOCATION] (
    POST_CODE VARCHAR(10),
    CITY VARCHAR(50),
    COUNTRY VARCHAR(50),
    CONSTRAINT PK_LOCATION PRIMARY KEY (POST_CODE, CITY)
);

-- Unit table
CREATE TABLE [UNIT] (
    UNIT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    UNIT_NAME VARCHAR(20)
);

-- Data table
CREATE TABLE [DATA] (
    DATA_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_ID BIGINT,
    DATA_ENTRY_TIME DATETIME,
    MEASSUREMENT_ENTRY_TIME DATETIME,
    VALUE VARCHAR(20),
    SUGAR_VALUE DECIMAL(5,2),
    REFERENCE_VALUE VARCHAR(20),
    UNIT_ID BIGINT,
    STATUS VARCHAR(20),
    FOREIGN KEY (USER_ID) REFERENCES [USER](USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (UNIT_ID) REFERENCES [UNIT](UNIT_ID)
);

-- Measurement table
CREATE TABLE [MEASURE] (
    MEASSURE_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    DATA_ID BIGINT,
    UNIT_ID BIGINT,
    SUGAR_VALUE DECIMAL(10,2),
    FOREIGN KEY (DATA_ID) REFERENCES [DATA](DATA_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES [UNIT](UNIT_ID)
);

-- Medication table
CREATE TABLE [MEDICATION] (
    MEDICATION_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_ID BIGINT,
    MEDICATION_NAME VARCHAR(50),
    FOREIGN KEY (USER_ID) REFERENCES [USER](USER_ID) ON DELETE CASCADE
);